#pragma once

#include "XMakina_Emulator_entities.h"

#ifndef DEBUGGER_H
#define DEBUGGER_H

extern union XMakina_memory memory;
extern union XMakina_register_file register_file;
extern char program_name[MAX_PROG_NAME_SIZE];

enum MENU_OPTIONS {BREAKPOINTS = 'B', RUN_PROGRAM = 'R', QUIT_PROGRAM = 'Q', VIEW_REG_FILE = 'F', VIEW_MEMORY = 'M', PROGRAM_STEP = '\0', SANITY_CHECK = 'S', LOAD_PROGRAM = 'L', MENU_OPTIONS = 'H'};
enum BREAKPOINT_MENU {VIEW_CURRENT_BREAKPOINTS = 'V', SET_MEM_BREAKPOINT = 'M', SET_CLOCK_OFFSET_BREAKPOINT = 'O', PRIORITY_CHANGE_BREAKPOINT = 'P', BACK_TO_DEBUGGER_MENU = 'Q'};
enum VIEW_REG_FILE_MENU {CHANGE_REG_VALUE = 'C', BACK_TO_DEBUGGER_MENU = 'Q'};
enum VIEW_MEMORY_MENU {TOP_BOTTOM_LIMIT_MEM_VIEW = 'L', BASE_AND_RANGE_MEM_VIEW = 'R', CHANGE_MEM_VALUE = 'C', BACK_TO_DEBUGGER_MENU = 'Q'};
enum SANITY_CHECK_MENU {VIEW_CURRENT_SANITY_CHECK = 'S', CHANGE_SANITY_CHECK_VALUE = 'C', BACK_TO_DEBUGGER_MENU = 'Q'};
char debugger();

#endif // !DEBUGGER_H
